# Generated by Django 3.2.20 on 2024-04-28 23:50

from django.db import migrations
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    def crear_usuario(apps, schema_editor):

        security = apps.get_model('security', 'User')

        security.objects.create(
            username='pruebas',
            password=make_password('pruebas2024'),
            first_name='Pruebas',
            last_name='Smartdoctor',
            role=1
        )

    operations = [
        migrations.RunPython(crear_usuario),
    ]
