# Generated by Django 3.2.20 on 2024-04-27 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('names', models.CharField(max_length=50, verbose_name='Names')),
                ('surnames', models.CharField(max_length=50, verbose_name='Surnames')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Cell phone')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('names', models.CharField(max_length=50, verbose_name='Names')),
                ('surnames', models.CharField(max_length=50, verbose_name='Surnames')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Cell phone')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_appointment', models.DateField(verbose_name='Fecha cita')),
                ('hour_appointment', models.TimeField(verbose_name='Fecha cita')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointment.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointment.specialist')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointment.specialty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
