# Generated by Django 3.2.23 on 2024-04-27 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_appointment', '0002_auto_20240427_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
